bet_dict = {'data': 'bets',
            'url_suffix': '_lines.htm',
            'table_id': 'vegas_lines'}

stat_dict = {'data': 'stats',
             'url_suffix': '.htm',
             'table_id': 'games'}

team_dict = {'crd': ['Arizona Cardinals'],
             'atl': ['Atlanta Falcons'],
             'rav': ['Baltimore Ravens'],
             'buf': ['Buffalo Bills'],
             'car': ['Carolina Panthers'],
             'chi': ['Chicago Bears'],
             'cin': ['Cincinnati Bengals'],
             'cle': ['Cleveland Browns'],
             'dal': ['Dallas Cowboys'],
             'den': ['Denver Broncos'],
             'det': ['Detroit Lions'],
             'gnb': ['Green Bay Packers'],
             'htx': ['Houston Texans'],
             'clt': ['Indianapolis Colts'],
             'jax': ['Jacksonville Jaguars'],
             'kan': ['Kansas City Chiefs'],
             'rai': ['Oakland Raiders', 'Las Vegas Raiders'],
             'sdg': ['San Diego Chargers', 'Los Angeles Chargers'],
             'ram': ['St. Louis Rams', 'Los Angeles Rams'],
             'mia': ['Miami Dolphins'],
             'min': ['Minnesota Vikings'],
             'nwe': ['New England Patriots'],
             'nor': ['New Orleans Saints'],
             'nyg': ['New York Giants'],
             'nyj': ['New York Jets'],
             'phi': ['Philadelphia Eagles'],
             'pit': ['Pittsburgh Steelers'],
             'sfo': ['San Francisco 49ers'],
             'sea': ['Seattle Seahawks'],
             'tam': ['Tampa Bay Buccaneers'],
             'oti': ['Tennessee Titans'],
             'was': ['Washington Redskins', 'Washington Commanders']}